name: Release SocialBar

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package and release to CurseForge
        uses: BigWigsMods/packager@v2
        with:
          addon-directory: SocialBar
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CURSEFORGE_PROJECT_ID: ${{ secrets.CF_PROJECT_ID }}
